version: 0.2
env:
  secrets-manager:
    SONAR_TOKEN: SONAR_TOKEN:sonartoken
    SNYK_KEY: SNYK_KEY:snykkey
  parameter-store:
    SONAR_PROJECT: "sonarproject"
    SONAR_ORG: "sonarorg"
    SONAR_HOST: "sonarhost"

phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      #Static Application Security Scan (SAST scan) using SonarCloud
      - mvn verify sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT -Dsonar.organization=$SONAR_ORG -Dsonar.host.url=$SONAR_HOST -Dsonar.token=$SONAR_TOKEN

      #Quality Gates for Static Application Security Scan(SAST) using SonarCloud

      - sleep 5
      - |-
        quality_status=$(curl -s -u $SONAR_TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=javaprojectaws | jq -r '.projectStatus.status')
        echo "SonarCloud analysistatus is $quality_status";
      #        if [ $quality_status = "ERROR" ] ; then exit 1;fi
      #Software Composition Analysis Scan (SCA scan) using Snyk

      - |-
        apt-get update
        apt-get -y install maven 
        SNYK_TOKEN=$SYNK_KEY
        export SNYK_TOKEN
        mvn snyk:test -fn

      #Dynamic Application Security Scan (DAST scan) using OWASP ZAP

      - |-
        apt-get update
        apt-get -y install wget
        apt-get -y install default-jdk
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
        tar -xvf ZAP_2.14.0_Linux.tar.gz
        cd ZAP_2.14.0
        ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html

#Storing DAST Reports in S3 bucket

artifacts:
  files:
    - zap_report.html
